

import java.io.*;
import java.sql.*;
import jakarta.servlet.*;
import jakarta.servlet.http.*;

public class companySignup extends HttpServlet {

    public void doPost(HttpServletRequest req, HttpServletResponse res)
            throws IOException, ServletException {

        res.setContentType("text/html");
        PrintWriter pw = res.getWriter();

        String companyName = req.getParameter("company");
        String email = req.getParameter("email");
        String contact = req.getParameter("contact");
        String address = req.getParameter("location");
        String password = req.getParameter("password");

        try {

            Class.forName("oracle.jdbc.driver.OracleDriver");

            Connection conn = DriverManager.getConnection(
                "jdbc:oracle:thin:@localhost:1521:XE",
                "system",
                "manager"
            );

            String sql = "INSERT INTO COMPANY " +
                         "(COMPANY_NAME, EMAIL_ID, CONTACT_NUMBER, OFFICE_ADDRESS, PASSWORD) " +
                         "VALUES (?, ?, ?, ?, ?)";

            PreparedStatement ps = conn.prepareStatement(sql);

            ps.setString(1, companyName);
            ps.setString(2, email);
            ps.setString(3, contact);
            ps.setString(4, address);
            ps.setString(5, password);

            ps.executeUpdate();

            // Get the company ID generated by the trigger
            String idQuery =
                "SELECT COMPANY_ID FROM COMPANY WHERE EMAIL_ID = ?";

            PreparedStatement ps2 = conn.prepareStatement(idQuery);
            ps2.setString(1, email);

            ResultSet rs = ps2.executeQuery();

            if (rs.next()) {

                String companyId = rs.getString("COMPANY_ID");

                pw.println("<html>");
                pw.println("<head>");
                pw.println("<title>Registration Successful</title>");
                pw.println("</head>");

                pw.println("<body>");

                pw.println("<h1>Registration Successful!</h1>");

                pw.println("<h3>Your Company ID is:</h3>");

                pw.println("<h2>" + companyId + "</h2>");

                pw.println("<p>Please save this Company ID.");
                pw.println("You will need it to login.</p>");

                pw.println("<a href='companySignin.html'>Go to Login</a>");

                pw.println("</body>");
                pw.println("</html>");
            }

            conn.close();

        } catch (Exception e) {
            pw.println("<h3>Error: " + e + "</h3>");
        }
    }
}